name: cmake-build-and-test
description: 'Run cmake --build && ctest'
inputs:
  os:
    required: true
runs:
  using: "composite"
  steps:
    - name: Check preconditions
      shell: bash
      run: |
        if [ -z "$PREFIX" ] ; then
          echo "PREFIX envvar is undefined"
          exit 1
        fi
    - name: Build
      shell: bash
      run: cmake --build --preset default --parallel
    - name: Test
      shell: bash
      run: >
        LD_LIBRARY_PATH="$PREFIX/lib"
        COVERAGE_PROFILE_DIR=coverage.profraw
        ctest --preset default
    - uses: ./.github/actions/gather-test-artifacts
      with:
        os: ${{ inputs.os }}
