image: archlinux/archlinux:base-devel

.build_dependencies: &build_dependencies
    - pacman --noconfirm -Sy cmake curl duktape pcre2 # TODO: clang?

# Note: these build steps include clang-format implicitly via CMAKE_C_CPPLINT
.build_steps: &build_steps
    - cmake -Wdev -Werror=dev -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=1 . -B ./build
    - cmake --build ./build
    - cd ./build/tests && ctest .

build_with_gcc:
  stage: build
  before_script:
    - *build_dependencies
  script:
    - export CC=gcc
    - export CXX=g++
    - *build_steps

build_with_clang:
  stage: build
  before_script:
    - *build_dependencies
  script:
    - export CC=clang
    - export CXX=clang++
    - *build_steps

# TODO: add gcc-12 variant, to somewhat cover openbsd 7.5 compat
