image: debian:unstable-slim

.build_dependencies: &build_dependencies
    - apt-get update
    - apt-get install --yes cmake clang duktape-dev git libcurl4-openssl-dev libpcre2-dev libseccomp-dev

# TODO: add -Werror=dev back: https://github.com/cpm-cmake/CPM.cmake/pull/570
# TODO: enable sandbox-landlock if CI runners start supporting landlock APIs
.build_steps: &build_steps
    - cmake -Wdev -Wno-error=dev -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=1 . -B ./build
    - cmake --build ./build
    - cd ./build/tests && ctest --output-junit junit.xml -E '^cli-try-sandbox|sandbox-landlock$' .

build_with_gcc:
  stage: build
  before_script:
    - *build_dependencies
  script:
    - export CC=gcc
    - export CXX=g++
    - *build_steps
  artifacts:
    when: always
    paths:
      - ./build/tests/junit.xml
    reports:
      junit: ./build/tests/junit.xml

build_with_clang:
  stage: build
  before_script:
    - *build_dependencies
  script:
    - export CC=clang
    - export CXX=clang++
    - *build_steps
  artifacts:
    when: always
    paths:
      - ./build/tests/junit.xml
    reports:
      junit: ./build/tests/junit.xml

# TODO: add -Werror=dev back: https://github.com/cpm-cmake/CPM.cmake/pull/570
format:
  stage: build
  before_script:
    - *build_dependencies
  script:
    - cmake -Wdev -Wno-error=dev -DCMAKE_BUILD_TYPE=Debug . -B ./build
    - cmake --build ./build --target fmt
