name: make-homebrew-devenv
description: 'Make and configure a Homebrew-based dev environment'
inputs:
  os:
    required: true
  compiler:
    required: true
  package:
    required: true
  preset:
    required: true
runs:
  using: "composite"
  steps:
    - name: Compute a unique ID for this job
      shell: bash
      run: |
        echo -n "ID=" >> "$GITHUB_ENV"
        if [ "${{ inputs.os }}" = "macos-13" ] ; then
          echo -n "macos-amd64"
        else
          echo -n "${{ inputs.os }}"
        fi >> "$GITHUB_ENV"
        echo "-${{ inputs.compiler }}-${{ inputs.preset }}" >> "$GITHUB_ENV"
    - uses: Homebrew/actions/setup-homebrew@master
    - name: Kludge for Homebrew cache filetype issues
      shell: bash
      if: startsWith(inputs.os, 'macos-')
      run: |
        sudo rm -rf                             \
          /opt/homebrew/share/gdb/auto-load/opt \
          /opt/homebrew/share/gettext/projects  \
          /opt/homebrew/share/gettext/schema    \
          /opt/homebrew/share/gettext/styles    \
          /opt/homebrew/share/gettext/po
    - uses: tecolicom/actions-use-homebrew-tools@v1
      with:
        tools: ${{ inputs.package }} cmake ada-url curl duktape jansson pcre2
        key: BUMP=0
    - name: Kludge for Homebrew cache permission issues, and install OS-specific packages
      shell: bash
      if: startsWith(inputs.os, 'ubuntu-')
      run: |
        sudo chown -R runner /home/linuxbrew/.linuxbrew/
        brew install libseccomp
    - name: Change $SHELL to bash on Ubuntu
      shell: bash
      if: startsWith(inputs.os, 'ubuntu-')
      run: |
        sudo rm -f /bin/sh && sudo ln -s /bin/{bash,sh}
    - name: Determine Homebrew prefix
      shell: bash
      run: |
        if [ -n "$(brew --prefix)" ] ; then
          echo "PREFIX=$(brew --prefix)"
        else
          echo "PREFIX=/usr/local"
        fi >> "$GITHUB_ENV"
    - name: Determine CC, accounting for Homebrew weirdness
      shell: bash
      run: |
        # For reference on this idiom for checking if a glob matched, see:
        #   https://unix.stackexchange.com/a/298302
        shopt -s nullglob
        for match in $PREFIX/bin/${{ inputs.compiler }}-[0-9]* ; do
          echo "CC=$match" >> "$GITHUB_ENV"
          exit 0
        done
        for match in $(brew --prefix llvm)/bin/${{ inputs.compiler }}-[0-9]* ; do
          echo "CC=$match" >> "$GITHUB_ENV"
          exit 0
        done
        echo "No CC found"
        exit 1
    - uses: ./.github/actions/cmake-configure
      with:
        preset: ${{ inputs.preset }}
