name: cmake-configure
description: 'Run cmake (configure)'
inputs:
  preset:
    required: true
runs:
  using: "composite"
  steps:
    - name: Check preconditions
      shell: bash
      run: |
        if [ -z "$PREFIX" ] ; then
          echo "PREFIX envvar is undefined"
          exit 1
        elif [ -z "$CC" ] ; then
          echo "CC envvar is undefined (explicit CC value is expected)"
          exit 1
        fi
    - name: Configure via cmake
      shell: bash
      run: >
        CFLAGS="-I$PREFIX/include"
        LDFLAGS="-L$PREFIX/lib"
        cmake --preset ${{ inputs.preset }}
        -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
        -DCMAKE_EXPORT_COMPILE_COMMANDS=1
