#!/usr/bin/env bash

set -euo pipefail

OUTPUT_FILE="$1"
shift

echo "/* Generated by $0 */" > "$OUTPUT_FILE"
echo '#include "coverage.h"' >> "$OUTPUT_FILE"
echo '#include "greatest.h"' >> "$OUTPUT_FILE"
echo 'GREATEST_MAIN_DEFS();' >> "$OUTPUT_FILE"

for filename ; do # iterate over remaining positional parameters
	entrypoint=$(basename -s .c "$filename")
	sed -n 's@^SUITE(\(.*\))@SUITE_EXTERN(\1);@p' "$filename"
	echo -e "int ${entrypoint}(int argc, char **argv);"
	echo -e "int ${entrypoint}(int argc, char **argv)"
	echo -e '{'
	echo -e '\tint fd __attribute__((cleanup(coverage_cleanup))) ='
	echo -e '\t\tcoverage_open();'
	echo -e '\tGREATEST_MAIN_BEGIN();'
	sed -n 's@^SUITE(\(.*\))@\tRUN_SUITE(\1);@p' "$filename"
	echo -e '\tGREATEST_MAIN_END();'
	echo -e '}'
done >> "$OUTPUT_FILE"
