include_guard(GLOBAL)

macro(adjust_global_includes_and_libraries)
	if (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
		if (IS_DIRECTORY /opt/homebrew)
			message(STATUS "Use libraries installed via Homebrew")
			include_directories(SYSTEM /opt/homebrew/include)
			link_directories(/opt/homebrew/lib)
		endif (IS_DIRECTORY /opt/homebrew)
	elseif (CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
		message(STATUS "Use libraries installed via OpenBSD ports")
		include_directories(SYSTEM /usr/local/include)
		link_directories(/usr/local/lib)
	endif ()
endmacro()
