name: multi-platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  # required by cpp-linter/cpp-linter-action@v2 for files-changed-only: false
  contents: read
  # required by EnricoMi/publish-unit-test-result-action@v2
  checks: write
  pull-requests: write

jobs:
  build-all:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
        toolchain:
          - compiler: gcc
            package: gcc
            preset: default
          - compiler: clang
            package: llvm
            preset: default
    runs-on: ${{ matrix.os }}
    steps:
    - uses: ./.github/actions/make-homebrew-devenv
      with:
        os: ${{ matrix.os }}
        compiler: ${{ matrix.toolchain.compiler }}
        package: ${{ matrix.toolchain.package }}
        preset: ${{ matrix.toolchain.preset }}
    - uses: ./github/actions/cmake-build-and-test
      with:
        os: ${{ matrix.os }}
  
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/make-homebrew-devenv
      with:
        os: ubuntu-latest
        compiler: clang
        package: llvm
        preset: default
    - name: Run clang-format and clang-tidy, including clang-analyzer checks
      id: lint
      uses: cpp-linter/cpp-linter-action@v2
      with:
        style: 'file'   # use .clang-format
        tidy-checks: '' # use .clang-tidy
        version: 19     # use clang-{format,tidy}-19
        database: ./build/
        ignore: ./build/
        files-changed-only: false
        file-annotations: true
        step-summary: true
    - name: Fail job if clang-format or clang-tidy found problems
      if: steps.lint.outputs.checks-failed > 0
      run: exit 1
  
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/make-homebrew-devenv
      with:
        os: ubuntu-latest
        compiler: clang
        package: llvm
        preset: coverage
    - uses: ./github/actions/cmake-build-and-test
      with:
        os: ubuntu-latest
    - name: Gather code coverage data
      run: |
        echo '```' >> "$GITHUB_STEP_SUMMARY"
        ./scripts/coverage.sh       \
          -E 'main.c|linuxbrew'     \
          coverage.profraw ./build/coverage.xml >> "$GITHUB_STEP_SUMMARY"
        echo >> "$GITHUB_STEP_SUMMARY"
        echo '```' >> "$GITHUB_STEP_SUMMARY"
    - name: Fail job if code coverage falls below threshold
      uses: VeryGoodOpenSource/very_good_coverage@v2
      with:
        path: ./build/coverage.lcov
        min_coverage: 100
        exclude: '/home/linuxbrew/.linuxbrew/include/** **/main.c'
  
  build-openbsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and test
      uses: vmactions/openbsd-vm@v1
      with:
        prepare: pkg_add cmake git ada curl duktape jansson pcre2
        run: >
          cmake --preset default &&
          cmake --build --preset default &&
          ctest --preset default
    - name: Compute a unique ID for openbsd job
      run: |
        echo "ID=openbsd" >> "$GITHUB_ENV"
    - uses: ./.github/actions/gather-test-artifacts
      with:
        os: openbsd
